### ISSUE TITLE
Recompile gwt on no changes

### ISSUE THREAD

**Issue by zufarfakhurtdinov** [tbroyer/gwt-maven-archetypes#39] opened 2016-02-29 18:10 UTC
I've generate project from **modular-webapp** archetype.
So, when I do **mvn package** it starts gwt compilation every time.
With -X property it prints: 

 Source file is newer than nocache.js, recompiling: /Users/zufarfakhurtdinov/dev/samples/gwtpluginsample3/gwtarchetypesample/gwtarchetypesample-shared/target/gwtarchetypesample-shared-1.0-SNAPSHOT-sources.jar

**Comment by tbroyer** [comment] 2016-02-29 19:35
Any idea why the sources jar has been rebuilt? It shouldn't be if there are no changes (at least according to documentation)

Maybe you could post the full log as gist?

**Comment by zufarfakhurtdinov** [comment] 2016-03-01 09:36
https://gist.github.com/zufarfakhurtdinov/a8fe415308f83b33e972
Full gist. I just change plugin version to 1.0-rc-6. No effect

**Comment by tbroyer** [comment] 2016-03-01 10:05
This is the culprit: https://gist.github.com/zufarfakhurtdinov/a8fe415308f83b33e972#file-gistfile1-txt-L1098

> `[DEBUG] isUp2date: false (Resource with unknown modification date found.)`

Now we'd need to understand which resource has a _zero_ modification time. I'll see if I reproduce locally and will try to debug it.

**Comment by tbroyer** [comment] 2016-03-01 14:31
OK, so the problem is that the maven-compiler-plugin:3.2 creates directory `target/generated-sources/annotations` and adds it as a source root, and maven-source-plugin (through maven-archiver → plexus-archiver → plexus-io) treats an empty directory as "having changed" (and that directory is always empty as there's no annotation processor involved).

Using maven-compiler-plugin:3.1 (which won't add `target/generated-sources/annotations` to the source roots; see https://issues.apache.org/jira/browse/MCOMPILER-157) will workaround the problem (until you need to use an annotation processor, in which case you should try maven-compiler-plugin:3.5.1 which _should_ behave correctly/sensibly).

**Comment by tbroyer** [comment] 2016-03-01 15:13
Fixed in 2247532a2fb8ec4d9508ea2e3a34dda291721925, thanks for the report.

**Closed by tbroyer** 2016-03-01 15:13 UTC
